eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/
#register url to server    

instance:
  hostname: localhost

server:
   port: 8090
---
spring:
  cloud:
    gateway:
      routes:
        - id: company
          uri: http://localhost:8091/
          predicates:
            - Path=/company/**
        - id: stock
          uri: http://localhost:8092/
          predicates:
            - Path=/stock/**
        - id: viewCompanyStock
          uri: http://localhost:8093/
          predicates:
            - Path=/viewCompanyStock/** 
            